"""Remove kcoder from this Mac: the app bundle, the launch agent, the daemon,
caches and the package. Session history and saved keys are kept unless the
user asks for them to go.

The work is done by a generated bash script that runs detached, because the
daemon that receives the request (or the CLI running `kcoder uninstall`)
is itself part of what gets removed.
"""

from __future__ import annotations

import os
import shlex
import subprocess
import sys
import tempfile

from . import paths
from . import app as appmod
from . import updater

# user data that survives by default
HISTORY = [paths.SESSIONS_DIR, paths.USAGE_LOG_PATH, os.path.join(paths.DATA_DIR, "commits.jsonl"),
           os.path.join(paths.DATA_DIR, "worktrees")]
KEYS = [paths.CREDENTIALS_PATH]
# always removed
CACHES = [os.path.join(paths.DATA_DIR, d) for d in ("webview", "app-profile", "updates")] + [
    paths.TOKEN_PATH, paths.DAEMON_INFO_PATH, paths.SOCKET_PATH, paths.UI_STATE_PATH,
    os.path.join(paths.DATA_DIR, "identity.json"), paths.DAEMON_LOG_PATH, paths.UPDATE_LOG_PATH,
    os.path.join(paths.DATA_DIR, "app.log"),
]


def plan(delete_history: bool, delete_keys: bool) -> list:
    steps = [("stop kcoderd and the login item", appmod.AGENT_PLIST),
             ("remove the app", appmod.BUNDLE_PATH),
             ("remove caches, token and logs", paths.DATA_DIR)]
    if delete_history:
        steps.append(("DELETE session history, usage stats and worktrees", ", ".join(HISTORY)))
    else:
        steps.append(("keep session history", paths.SESSIONS_DIR))
    if delete_keys:
        steps.append(("DELETE saved provider keys", paths.CREDENTIALS_PATH))
    else:
        steps.append(("keep saved provider keys", paths.CREDENTIALS_PATH))
    if updater.is_dev_install():
        steps.append(("leave the developer checkout alone", updater.checkout_root()))
    else:
        steps.append(("pip uninstall kcoder", sys.executable))
    return steps


def script(delete_history: bool, delete_keys: bool, wait_pid: int | None = None, pip: bool = True) -> str:
    q = shlex.quote
    lines = ["#!/bin/bash", "# kcoder uninstall, generated by kcoder", "set +e",
             f"echo \"kcoder uninstall started $(date)\""]
    if wait_pid:
        lines += [f"for i in $(seq 1 300); do kill -0 {wait_pid} 2>/dev/null || break; sleep 0.1; done",
                  f"kill -0 {wait_pid} 2>/dev/null && kill -TERM {wait_pid} 2>/dev/null; sleep 0.5"]
    isolated = bool(os.environ.get("KCODER_DATA_DIR") or os.environ.get("KCODER_PORT"))   # tests: only our own files
    if sys.platform == "darwin":
        if not isolated:
            lines.append(f"launchctl bootout gui/$(id -u)/{appmod.AGENT_LABEL} 2>/dev/null")
        lines.append(f"rm -f {q(appmod.AGENT_PLIST)}")
        if not isolated:
            lines.append("pkill -f 'kcoder.cli app' 2>/dev/null; pkill -f 'python.*-m kcoder.app' 2>/dev/null")
        lines.append(f"rm -rf {q(appmod.BUNDLE_PATH)}")
    if not isolated:
        lines.append("pkill -f 'python.*-m kcoder.daemon' 2>/dev/null")
    for p in CACHES:
        lines.append(f"rm -rf {q(p)}")
    if delete_history:
        for p in HISTORY:
            lines.append(f"rm -rf {q(p)}")
    if delete_keys:
        for p in KEYS:
            lines.append(f"rm -f {q(p)}")
    if pip and not updater.is_dev_install():
        lines.append(f"{q(sys.executable)} -m pip uninstall -y -q kcoder 2>&1 | tail -1")
    elif updater.is_dev_install():
        lines.append(f"echo 'developer checkout at {updater.checkout_root()} left in place (pip install -e)'")
    lines += [f"rmdir {q(paths.DATA_DIR)} 2>/dev/null",
              f"rmdir {q(paths.CONFIG_DIR)} 2>/dev/null",
              "echo \"kcoder uninstall finished $(date)\"",
              "rm -f \"$0\""]
    return "\n".join(lines) + "\n"


def run(delete_history: bool, delete_keys: bool, *, wait_pid: int | None = None,
        pip: bool = True, detach: bool = True, dry_run: bool = False) -> str:
    """Write the script and run it (detached by default). Returns the script path or text (dry run)."""
    text = script(delete_history, delete_keys, wait_pid, pip)
    if dry_run:
        return text
    fd, path = tempfile.mkstemp(prefix="kcoder-uninstall-", suffix=".sh")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(text)
    os.chmod(path, 0o700)
    log = os.path.join(tempfile.gettempdir(), "kcoder-uninstall.log")
    if detach:
        with open(log, "a") as lf:
            subprocess.Popen(["/bin/bash", path], stdin=subprocess.DEVNULL, stdout=lf, stderr=lf,
                             start_new_session=True, close_fds=True, cwd=os.path.expanduser("~"))
    else:
        subprocess.run(["/bin/bash", path])
    return path
